"""
Generate the plots reporting Fmeasure for the computed edge surfaces
with Sobel filter and EK filter from the synthetic images, compared
with the known ideal edge surfaces.
This is done by reading the files ouput by running
  ../precision_recall.py 
with script
  ../make_synt_measure
"""

# ========================================================================
# Reading function: read the output of ../precision_recall.py
# (that has been generated through ../make_synt_measure

def read_one_file(file, thresholds):
  """
  Read a file output by ../make_synt_measure and obtain the
  precision and recall data. Such data have been computed, and are present 
  in the file, in exact way (EXACT), within distance 2 (D2) and 3 (D3).
  The thresholds are a list of sorted values, and must match the ones
  present in the file.
  Return a dictionary where key=a threshold and
  value = (L1, L2) where L1 = list of precisions (one for each
  distance) and L2 = list of recalls (one for each distance).
  """
  # The following strings must match the content of the files
  # generated from ../precision_recall.py
  separ = "============ F measure ============"
  prefix1 = "Ideal image"
  prefix2 = "Computed image"
  subfix1 = "(values<= "
  subfix2 = " considered as 0)"
  distances = ["EXACT","D2","D3"]

  F = open(file,"r")
  lines = F.readlines()
  lines = [lin for lin in lines if len(lin)>0]
  for i in range(len(lines)):
    if lines[i][-1]=='\n': lines[i] = lines[i][:len(lines[i])-1]
  ind = 0
  all_data = dict()
  for t in range(len(thresholds)):
    assert lines[ind].startswith(separ)
    assert lines[ind+1].startswith(prefix1)
    assert lines[ind+2].startswith(prefix2)
    if thresholds[t]>1:
      assert lines[ind+2].endswith(subfix1+str(thresholds[t])+subfix2)
    else:
      assert lines[ind+2].endswith(".vtk")
    precisions = [0,0,0]
    recalls = [0,0,0]
    ind += 3
    for d in range(3):
      a,b,c = lines[ind].split()
      assert a == distances[d] and b == "Precision:"
      precisions[d] = float(c)
      a,b,c = lines[ind+1].split()
      assert a == distances[d] and b == "Recall:"
      recalls[d] = float(c)
      ind += 2
    all_data[thresholds[t]] = (precisions,recalls)
  return all_data


# ========================================================================
# Functions to compute the F-measure from precision and recall

def Fmeasure(prec,rec, beta=1):
  """
  Combine precision and recall into the F-measure.
  """
  return ( (1+beta**2)*prec*rec ) / ( (beta**2)*prec + rec )

def Fmeasure_data(dictionary, beta=1):
  """
  Input dictionary has key=threshold, value = two lists (precision,recall)
  where each list has 3 elements for the three distances 0,2,3.
  The input dictionary will have been generated by read_one_file.
  Output another dictionary with key=threshold, value = one list F-measure
  with 3 elements for the three distances 0,2,3
  """
  D = dict()
  for t in dictionary:
    pp = dictionary[t][0]
    rr = dictionary[t][1]
    ff = [Fmeasure(p,r, beta) for p,r, in zip(pp,rr)]
    D[t] = ff
  return D

# ========================================================================
# Plot function

from matplotlib import pyplot as plt

def Fmeasure_plot(directory, name, title, thresholds):
  """
  Read precision and recall data from the file of given name located
  in the given directory. The file contains precision and
  recall computed for the given list of thresholds.
  The title is to be put on top of the plot.
  """
  sobel_name = directory+"measureSobel_"+name+".txt"
  ek_name = directory+"measureEK_"+name+".txt" 
  sobel_data = read_one_file(sobel_name, thresholds)
  ek_data = read_one_file(ek_name, thresholds)

  # compute F-measure from data  
  sobel_data = Fmeasure_data(sobel_data)
  ek_data = Fmeasure_data(ek_data)
  
  # unpack data: from dictionary threshold-->Fmeasure to list of F-measures
  sob_d0 = [sobel_data[t][0] for t in thresholds]
  sob_d2 = [sobel_data[t][1] for t in thresholds]
  sob_d3 = [sobel_data[t][2] for t in thresholds]
  ek_d0  = [ek_data[t][0] for t in thresholds]
  ek_d2  = [ek_data[t][1] for t in thresholds]
  ek_d3  = [ek_data[t][2] for t in thresholds]

  # plot data
  fig, ax = plt.subplots()
  col1, col2 = "#ff9000", "black"

  ax.plot(thresholds, sob_d0, color=col1, marker="o",markersize=4,linewidth=2, label="Sobel")
  ax.plot(thresholds, sob_d2, color=col1, marker="o",markersize=3,linewidth=1.5)
  ax.plot(thresholds, sob_d3, color=col1, marker="o",markersize=2,linewidth=1)

  ax.plot(thresholds, ek_d0,  color=col2, marker="o",markersize=4,linewidth=1.75,linestyle='dashed', label="EK")
  ax.plot(thresholds, ek_d2,  color=col2, marker="o",markersize=3,linewidth=1.25,linestyle='dashed')
  ax.plot(thresholds, ek_d3,  color=col2, marker="o",markersize=2,linewidth=0.75,linestyle='dashed')
  
  #ax.set_box_aspect(1)
  ax.set_title(title, fontsize=18) 
  ax.legend(loc='lower center', fontsize=12)
  ax.set_xticks(thresholds)
  ax.set_yticks([0.1*y for y in range(11)]) 
  ax.set_xlabel("value threshold", fontsize=14)
  ax.set_ylabel("F-measure", fontsize=14)
  ax.grid(True)
  return fig, ax

# =====================  MAIN =========================================

def gen_names(name):
  return [name] + ["noisy_"+name+"_0"+s for s in ("16","32","64")]

def gen_titles(name):
  return ["clean "+name] + ["noisy "+name+" (variance"+s+")" for s in ("16","32","64")]

def main_Fmeasure():
  # The list of threshold must match the thresholds present in the files
  thresholds = [1,32,64,96,128,160,192,224]
  # Generate input file names and plot titles
  names_axis,    titles_axis    = gen_names("axis"),    gen_titles("axis")
  names_slanted, titles_slanted = gen_names("slanted"), gen_titles("slanted")
  names_sphere,  titles_sphere  = gen_names("sphere"),  gen_titles("sphere")
  all_names  = names_axis + names_slanted + names_sphere
  all_titles = titles_axis + titles_slanted + titles_sphere
  # Generate the plots and save them
  for name, title in zip(all_names,all_titles):
    f,a = Fmeasure_plot("./", name, title, thresholds)
    f.savefig("Fmeasure_"+name+".png")
  #plt.show()

if __name__=="__main__":
  main_Fmeasure()
